name: cv

services:
  fastapi:
    container_name: cv-fastapi
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/cv-fastapi:ro
    depends_on:
      - postgres
    environment:
      POSTGRES_HOSTNAME: postgres
      MEDIA_FOLDER_PATH: /cv-fastapi/media
  postgres:
    container_name: cv-postgres
    image: postgres:13.20
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgresql_data:
